[build]
publish = "frontend/dist"
command = "npm run build"

[functions]
directory = "backend/src/netlify/functions"
node_bundler = "esbuild"


[dev]
framework = "#custom"
command = "npm --workspace frontend run dev"
targetPort = 5173
port = 8899
functions = "backend/dist/netlify/functions"
