[dev]
  framework = "#custom"
  port = 8899
  staticServerPort = 4000

[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "backend/dist/netlify/functions"
